#I pledge my honor that I have abided by the Stevens Honor System -Bsoong
cs392_thread : cs392_thread.o
		gcc -o cs392_thread cs392_thread.o -pthread
clean :
	 	rm -rf  *.o cs392_thread
cs392_thread.o : cs392_thread.c
			gcc -c -g cs392_thread.c
